const regionList = [
  {
    id:1,
    name:'指挥大厅',
    screenList:[
      {
        id:1,
        name:'中心大屏',
        src:'image/icon_screen1.png'
      },{
        id:2,
        name:'侧屏1',
        src:'image/icon_screen2.png'
      },{
        id:3,
        name:'投影1',
        src:'image/icon_screen3.png'
      },{
        id:4,
        name:'投影2',
        src:'image/icon_screen4.png'
      }
    ]
  },
  {
    id:2,
    name:'二楼会议室',
    screenList:[
      {
        id:1,
        name:'中心大屏',
        src:'image/icon_screen1.png'
      },{
        id:2,
        name:'投影1',
        src:'image/icon_screen2.png'
      },{
        id:3,
        name:'投影2',
        src:'image/icon_screen3.png'
      }
    ]
  },
  {
    id:3,
    name:'会议室2',
    screenList:[
      {
        id:1,
        name:'中心大屏',
        src:'image/icon_screen1.png'
      },{
        id:2,
        name:'投影1',
        src:'image/icon_screen2.png'
      },{
        id:3,
        name:'投影2',
        src:'image/icon_screen3.png'
      },{
        id:4,
        name:'投影3',
        src:'image/icon_screen4.png'
      }
    ]
  }
];
const signalList = [{
  id:1,
  src:"image/jpg2.png",
  title:'信号源1'
},{
  id:2,
  src:"image/jpg2.png",
  title:'信号源2'
},{
  id:3,
  src:"image/jpg2.png",
  title:'信号源3'
},{
  id:4,
  src:"image/jpg2.png",
  title:'信号源4'
},{
  id:5,
  src:"image/jpg2.png",
  title:'信号源5'
},{
  id:6,
  src:"image/jpg2.png",
  title:'信号源6'
},{
  id:7,
  src:"image/jpg2.png",
  title:'信号源7'
},{
  id:8,
  src:"image/jpg2.png",
  title:'信号源8'
},{
  id:9,
  src:"image/jpg2.png",
  title:'信号源9'
},{
  id:10,
  src:"image/jpg2.png",
  title:'信号源10'
},{
  id:11,
  src:"image/jpg2.png",
  title:'信号源11'
},{
  id:12,
  src:"image/jpg2.png",
  title:'信号源12'
}];
const sceneList =[
  {
    id:1,
    name:'场景1',
    layerList: [
      {
        id:1,
        top:0,
        left:0,
        width:65536/2,
        height:65536/2,
        src:"image/jpg2.png"
      },
      {
        id:2,
        top:0,
        left:65536/2,
        width:65536/2,
        height:65536/2,
        src:"image/jpg2.png"
      },
      {
        id:3,
        top:65536/2,
        left:0,
        width:65536/2,
        height:65536/2,
        src:"image/jpg2.png"
      },
      {
        id:4,
        top:65536/2,
        left:65536/2,
        width:65536/2,
        height:65536/2,
        src:"image/jpg2.png"
      }
    ]
  },
  {
    id:2,
    name:'场景2',
    layerList: [
      {
        id:1,
        top:0,
        left:0,
        width:65536,
        height:65536,
        src:"image/jpg2.png"
      },
    ]
  },
  {
    id:3,
    name:'场景3',
    layerList: [
      {
        id:1,
        top:0,
        left:0,
        width:65536/2,
        height:65536,
        src:"image/jpg2.png"
      },
      {
        id:2,
        top:0,
        left:65536/2,
        width:65536/2,
        height:65536,
        src:"image/jpg2.png"
      }
    ]
  },
  {
    id:4,
    name:'场景4',
    layerList: [
      {
        id:1,
        top:0,
        left:0,
        width:65536,
        height:65536/2,
        src:"image/jpg2.png"
      },
      {
        id:2,
        top:65536/2,
        left:0,
        width:65536,
        height:65536/2,
        src:"image/jpg2.png"
      },
    ]
  },
  {
    id:5,
    name:'场景5',
    layerList: [
      {
        id:1,
        top:0,
        left:0,
        width:65536,
        height:65536/2,
        src:"image/jpg2.png"
      },
      {
        id:2,
        top:65536/2,
        left:0,
        width:65536/2,
        height:65536/2,
        src:"image/jpg2.png"
      },
      {
        id:3,
        top:65536/2,
        left:65536/2,
        width:65536/2,
        height:65536/2,
        src:"image/jpg2.png"
      }
    ]
  },
  {
    id:6,
    name:'场景6',
    layerList: [
      {
        id:1,
        top:0,
        left:0,
        width:65536/2,
        height:65536,
        src:"image/jpg2.png"
      },
      {
        id:2,
        top:0,
        left:65536/2,
        width:65536/2,
        height:65536/2,
        src:"image/jpg2.png"
      },
      {
        id:3,
        top:65536/2,
        left:65536/2,
        width:65536/2,
        height:65536/2,
        src:"image/jpg2.png"
      },
    ]
  },
  {
    id:7,
    name:'场景7',
    layerList: [
      {
        id:1,
        top:0,
        left:0,
        width:65536/2,
        height:65536/2,
        src:"image/jpg2.png"
      },
      {
        id:2,
        top:0,
        left:65536/2,
        width:65536/2,
        height:65536/2,
        src:"image/jpg2.png"
      },
      {
        id:3,
        top:65536/2,
        left:0,
        width:65536,
        height:65536/2,
        src:"image/jpg2.png"
      },
    ]
  }
]


export default{
  regionList,
  signalList,
  sceneList
}